spring:
  datasource:
    url: 'jdbc:h2:mem:cf'
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8000      

